Repository softeerbootcamp-2nd/be-chess, pull requests merged in 2023-07, with the labels that each got.

#3 [Chocochip101] step-1 미션-1 기능 목록 Readme 생성
  .idea/misc.xml
  README.md
  ReadmeDir/Mission1.md
  src/main/java/softeer2nd/Pawn.java
  src/test/java/softeer2nd/PawnTest.java
Labels: study-plan

#12 [kwYoohae] step-1 study plan 작성
  README.md
Labels: study-plan

#8 [jongwon] Step-1 폰 생성
  .idea/.name
  .idea/misc.xml
  build.gradle
  src/main/java/chess/Board.java
  src/main/java/chess/pieces/Pawn.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: step-1

#13 [jst0951] step-1 폰 생성
  .idea/misc.xml
  src/main/java/softeer2nd/Pawn.java
  src/test/java/softeer2nd/PawnTest.java
Labels: step-1

#16 [SyuA0529] step-1 폰 생성
  .idea/compiler.xml
  .idea/misc.xml
  src/main/java/softeer2nd/Pawn.java
  src/test/java/softeer2nd/PawnTest.java
Labels: step-1

#24 [SEONMl] step-1 폰 생성
  .gitignore
  README.md
  src/main/java/softeer2nd/piece/Pawn.java
  src/test/java/softeer2nd/piece/PawnTest.java
Labels: step-1

#30 [Yunsik-Choi] step-1 폰 생성
  .idea/misc.xml
  README.md
  build.gradle
  src/main/java/softeer2nd/domain/Pawn.java
  src/test/java/softeer2nd/domain/PawnTest.java
Labels: step-1

#33 [kwYoohae] step-1 폰 생성
  README.md
  src/main/java/softeer2nd/Pawn.java
  src/test/java/softeer2nd/PawnTest.java
Labels: step-1

#39 [ddingmin] step-1 폰 생성
  README.md
  src/main/java/softeer2nd/chess/domain/piece/Pawn.java
  src/test/java/softeer2nd/PawnTest.java
Labels: step-1

#40 [SyuA0529] step-0 주간 학습 목표
  README.md
Labels: study-plan

#43 [jongwon] step-2 체스판 생성
  README.md
  src/test/java/chess/pieces/PawnTest.java
Labels: step-2

#46 [kwYoohae] step-2 체스판 생성
  README.md
  src/main/java/softeer2nd/Pawn.java
  src/main/java/softeer2nd/chess/Board.java
  src/main/java/softeer2nd/chess/exception/ExceptionMessage.java
  src/main/java/softeer2nd/chess/pieces/Pawn.java
  src/test/java/softeer2nd/PawnTest.java
  src/test/java/softeer2nd/chess/BoardTest.java
  src/test/java/softeer2nd/chess/pieces/PawnTest.java
Labels: step-2

#48 [Yunsik-Choi] step-2 체스판 생성
  .idea/misc.xml
  README.md
  src/main/java/softeer2nd/chess/Board.java
  src/main/java/softeer2nd/chess/pieces/Pawn.java
  src/test/java/softeer2nd/chess/BoardTest.java
  src/test/java/softeer2nd/chess/pieces/PawnTest.java
Labels: step-2

#57 [jst0951] step-2 체스판 생성
  .idea/misc.xml
  src/main/java/chess/Board.java
  src/main/java/chess/pieces/Pawn.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: step-2

#61 [SyuA0529] step-2 체스판 생성
  .idea/misc.xml
  src/main/java/softeer2nd/Pawn.java
  src/main/java/softeer2nd/chess/Board.java
  src/main/java/softeer2nd/chess/pieces/Pawn.java
  src/test/java/softeer2nd/PawnTest.java
  src/test/java/softeer2nd/chess/BoardTest.java
  src/test/java/softeer2nd/chess/pieces/PawnTest.java
Labels: step-2

#68 [SEONMl] step-2 체스판 생성
  .gitignore
  README.md
  src/main/java/softeer2nd/domain/Board.java
  src/main/java/softeer2nd/domain/ChessColor.java
  src/main/java/softeer2nd/domain/Pawn.java
  src/main/java/softeer2nd/piece/Pawn.java
  src/test/java/softeer2nd/domain/BoardTest.java
  src/test/java/softeer2nd/domain/PawnTest.java
  src/test/java/softeer2nd/piece/PawnTest.java
Labels: step-2

#72 [ddingmin] step-2 체스판 생성
  README.md
  src/main/java/softeer2nd/chess/Board.java
  src/main/java/softeer2nd/chess/domain/piece/Pawn.java
  src/main/java/softeer2nd/chess/pieces/Pawn.java
  src/test/java/softeer2nd/PawnTest.java
  src/test/java/softeer2nd/chess/BoardTest.java
  src/test/java/softeer2nd/chess/pieces/PawnTest.java
Labels: step-2

#75 [jongwon] step-3 체스판 초기화
  src/main/java/chess/Board.java
  src/main/java/chess/MainChess.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/softeer2nd/Main.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
Labels: step-3

#79 [jst0951] step-3 체스판 초기화
  src/main/java/chess/Board.java
  src/main/java/chess/Main.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/softeer2nd/Main.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/MainTest.java
  src/test/java/chess/pieces/PawnTest.java
  src/test/java/softeer2nd/HelloTest.java
Labels: step-3

#83 [SyuA0529] step-3 체스판 초기화
  src/main/java/softeer2nd/Main.java
  src/main/java/softeer2nd/chess/Board.java
  src/main/java/softeer2nd/chess/pieces/Pawn.java
  src/test/java/softeer2nd/chess/BoardTest.java
  src/test/java/softeer2nd/chess/pieces/PawnTest.java
Labels: step-3

#93 [SEONMl] step-3 체스판 초기화
  README.md
  src/main/java/softeer2nd/Main.java
  src/main/java/softeer2nd/controller/GameController.java
  src/main/java/softeer2nd/domain/Board.java
  src/main/java/softeer2nd/domain/ChessColor.java
  src/main/java/softeer2nd/domain/Pawn.java
  src/test/java/softeer2nd/domain/BoardTest.java
  src/test/java/softeer2nd/domain/PawnTest.java
Labels: step-3

#111 [jongwon] step-4: 기물 배치
  src/main/java/chess/Board.java
  src/main/java/chess/MainChess.java
  src/main/java/chess/StringUtils.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/chess/pieces/Piece.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
  src/test/java/chess/pieces/PieceTest.java
Labels: step-4

#115 [SyuA0529] step-4 기물 배치
  src/main/java/softeer2nd/Main.java
  src/main/java/softeer2nd/chess/Board.java
  src/main/java/softeer2nd/chess/board/Board.java
  src/main/java/softeer2nd/chess/pieces/Pawn.java
  src/main/java/softeer2nd/chess/pieces/Piece.java
  src/main/java/softeer2nd/utils/PositionUtils.java
  src/main/java/softeer2nd/utils/StringUtils.java
  src/test/java/softeer2nd/chess/BoardTest.java
  src/test/java/softeer2nd/chess/board/BoardTest.java
  src/test/java/softeer2nd/chess/pieces/PawnTest.java
  src/test/java/softeer2nd/chess/pieces/PieceTest.java
  src/test/java/softeer2nd/utils/PositionUtilsTest.java
  src/test/java/softeer2nd/utils/StringUtilsTest.java
Labels: step-4

#122 [jst0951] step-4 기물 배치
  src/main/java/chess/Board.java
  src/main/java/chess/Main.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/utils/StringUtils.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PawnTest.java
  src/test/java/chess/pieces/PieceTest.java
Labels: step-4

#148 [jst0951] step-5 기물 위치 부여 및 점수계산
  src/main/java/chess/Board.java
  src/main/java/chess/pieces/Piece.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PieceTest.java
Labels: step-5

#162 [jongwon] step-5 기물 위치 부여 및 점수계산
  src/main/java/chess/Board.java
  src/main/java/chess/Position.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/pieces/Rank.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/pieces/PieceTest.java
Labels: step-5

#209 [김종원] step-6 기물 이동 구현
  src/main/java/chess/Board.java
  src/main/java/chess/MainChess.java
  src/main/java/chess/Position.java
  src/main/java/chess/controller/ChessGame.java
  src/main/java/chess/controller/Direction.java
  src/main/java/chess/model/Position.java
  src/main/java/chess/model/board/Board.java
  src/main/java/chess/model/board/Rank.java
  src/main/java/chess/model/pieces/Bishop.java
  src/main/java/chess/model/pieces/King.java
  src/main/java/chess/model/pieces/Knight.java
  src/main/java/chess/model/pieces/NoPiece.java
  src/main/java/chess/model/pieces/Pawn.java
  src/main/java/chess/model/pieces/Piece.java
  src/main/java/chess/model/pieces/PieceColor.java
  src/main/java/chess/model/pieces/PieceCreator.java
  src/main/java/chess/model/pieces/PieceType.java
  src/main/java/chess/model/pieces/Queen.java
  src/main/java/chess/model/pieces/Rook.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/pieces/Rank.java
  src/main/java/chess/view/BoardView.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/BoardViewTest.java
  src/test/java/chess/ChessGameTest.java
  src/test/java/chess/pieces/BishopTest.java
  src/test/java/chess/pieces/KingTest.java
  src/test/java/chess/pieces/KnightTest.java
  src/test/java/chess/pieces/PawnTest.java
  src/test/java/chess/pieces/PieceTest.java
  src/test/java/chess/pieces/QueenTest.java
  src/test/java/chess/pieces/RookTest.java
Labels: step-6

#216 [정성태] step-6 기물 이동 구현
  src/main/java/Main.java
  src/main/java/chess/Board.java
  src/main/java/chess/Game.java
  src/main/java/chess/Main.java
  src/main/java/chess/Position.java
  src/main/java/chess/View.java
  src/main/java/chess/pieces/Bishop.java
  src/main/java/chess/pieces/Blank.java
  src/main/java/chess/pieces/King.java
  src/main/java/chess/pieces/Knight.java
  src/main/java/chess/pieces/Pawn.java
  src/main/java/chess/pieces/Piece.java
  src/main/java/chess/pieces/Queen.java
  src/main/java/chess/pieces/Rook.java
  src/test/java/MainTest.java
  src/test/java/chess/BoardTest.java
  src/test/java/chess/GameTest.java
  src/test/java/chess/PositionTest.java
  src/test/java/chess/ViewTest.java
  src/test/java/chess/pieces/BishopTest.java
  src/test/java/chess/pieces/BlankTest.java
  src/test/java/chess/pieces/KingTest.java
  src/test/java/chess/pieces/KnightTest.java
  src/test/java/chess/pieces/PawnTest.java
  src/test/java/chess/pieces/QueenTest.java
  src/test/java/chess/pieces/RookTest.java
Labels: step-6
